version: '3.4'
services:
  app:
    image: my-app-image
#    build:
#      context: .
    ports:
      - "8081:8081"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_MINIO_ENDPOINT: http://minio:9000
      SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200
    depends_on:
      - kafka
      - minio
      - elasticsearch
    volumes:
      - ./src/main/resources:/app/src/main/resources
    deploy:
      replicas: 2
    networks:
      - my-network

  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - my-network

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    depends_on:
      - zookeeper
    networks:
      - my-network

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ACCESS_KEY: "ROOTUSER"
      MINIO_SECRET_KEY: "CHANGEME123"
      MINIO_BUKET: "library"
    ports:
      - "9000:9000"
    command: server /data
    networks:
      - my-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - my-network

networks:
  my-network:
    driver: overlay
    attachable: true